#!/usr/bin/env python3
import sys
from decimal import Decimal, getcontext


def sqrt(x, n):
    """ Calculate the square root of a positive integer """

    def average(y, x):
        return (Decimal(y) + Decimal(x)) / 2

    def improve(y, x):
        return average(Decimal(y), x / Decimal(y))

    def abs(x):
        if x >= 0:
            return Decimal(x)
        else:
            return - Decimal(x)

    def good_enough(y, x, n):
        return abs((Decimal(y) * Decimal(y)) - x) < Decimal(1 / (10 ** n))

    def sqrt_iter(y, x, n):
        if good_enough(Decimal(y), x, n):
            return Decimal(y)
        else:
            return sqrt_iter(improve(Decimal(y), x), x, n)

    return sqrt_iter(Decimal(1.0), x, n)


if __name__ == '__main__':
    x = int(sys.argv[1])
    n = int(sys.argv[2])
    getcontext().prec = 51
    assert n <= 50, "Precisão precisa ser menor ou igual a 50"
    print("square root of {0} = {1:.{2}f}".format(x, sqrt(x, n), n))